name: todo
description: Todo App
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.2

  # Others
  get_it: ^7.2.0
  floor: ^1.4.1
  equatable: ^2.0.5
  auto_route: ^5.0.4
  dotted_border: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.4
  lint: ^2.0.1
  auto_route_generator: ^5.0.3
  floor_generator: ^1.4.1
  build_runner: ^2.3.3
  mockito: ^5.4.2
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true